import { Dish } from '../types/types';

// 扩展Dish类型以包含匹配算法所需的额外属性
interface DishWithMatchingData extends Dish {
  taste: string[];
  cookingTimeCategory: string;
  incompatibleWith: string[];
}

// 菜品数据库
export const dishes: DishWithMatchingData[] = [
  {
    id: '1',
    name: '麻婆豆腐',
    description: '经典川菜，以豆腐为主料，配以牛肉末，辣椒和花椒烹制而成。麻辣鲜香，口感丰富。',
    region: '四川',
    cuisine: '川菜',
    difficulty: '中等',
    cookingTime: '20分钟',
    cookingTimeCategory: '适中',
    suitableFor: '家庭主妇',
    spicyLevel: '麻辣',
    ingredients: ['豆腐', '牛肉末', '郫县豆瓣', '花椒', '葱姜蒜'],
    taste: ['麻辣', '鲜香'],
    incompatibleWith: ['素食'],
    reason: ''
  },
  {
    id: '2',
    name: '宫保鸡丁',
    description: '传统川菜，将鸡肉切成丁状，与花生米、干辣椒等炒制，口感香辣脆嫩。',
    region: '四川',
    cuisine: '川菜',
    difficulty: '中等',
    cookingTime: '25分钟',
    cookingTimeCategory: '适中',
    suitableFor: '上班族',
    spicyLevel: '中等',
    ingredients: ['鸡胸肉', '花生米', '干辣椒', '葱姜蒜', '黄瓜'],
    taste: ['麻辣', '香甜'],
    incompatibleWith: ['素食', '无麸质'],
    reason: ''
  },
  {
    id: '3',
    name: '番茄炒蛋',
    description: '家常菜品，将西红柿与鸡蛋一起烹制，酸甜可口，营养丰富。',
    region: '全国各地',
    cuisine: '家常菜',
    difficulty: '简单',
    cookingTime: '10分钟',
    cookingTimeCategory: '快速',
    suitableFor: '上班族',
    spicyLevel: '不辣',
    ingredients: ['西红柿', '鸡蛋', '葱', '盐', '糖'],
    taste: ['酸甜', '清淡'],
    incompatibleWith: ['素食'],
    reason: ''
  },
  {
    id: '4',
    name: '红烧肉',
    description: '经典家常菜，将五花肉慢炖至软烂，色泽红亮，肥而不腻。',
    region: '江浙',
    cuisine: '苏菜',
    difficulty: '中等',
    cookingTime: '60分钟',
    cookingTimeCategory: '耐心',
    suitableFor: '家庭主妇',
    spicyLevel: '不辣',
    ingredients: ['五花肉', '姜', '葱', '老抽', '冰糖'],
    taste: ['咸鲜', '浓郁'],
    incompatibleWith: ['素食', '低脂'],
    reason: ''
  },
  {
    id: '5',
    name: '水煮鱼',
    description: '四川名菜，将鱼片在沸水中烫熟后，浇上热油激发辣椒和花椒的香味。麻辣鲜香，口感嫩滑。',
    region: '四川',
    cuisine: '川菜',
    difficulty: '复杂',
    cookingTime: '40分钟',
    cookingTimeCategory: '耐心',
    suitableFor: '家庭主妇',
    spicyLevel: '重辣',
    ingredients: ['草鱼', '豆芽', '花椒', '干辣椒', '葱姜蒜'],
    taste: ['麻辣', '鲜香'],
    incompatibleWith: ['素食', '无海鲜'],
    reason: ''
  },
  {
    id: '6',
    name: '糖醋里脊',
    description: '经典粤菜，酸甜可口，外酥里嫩。将里脊肉炸至金黄，淋上糖醋汁。',
    region: '广东',
    cuisine: '粤菜',
    difficulty: '中等',
    cookingTime: '30分钟',
    cookingTimeCategory: '适中',
    suitableFor: '家庭主妇',
    spicyLevel: '不辣',
    ingredients: ['里脊肉', '淀粉', '醋', '糖', '番茄酱'],
    taste: ['酸甜', '浓郁'],
    incompatibleWith: ['素食'],
    reason: ''
  },
  {
    id: '7',
    name: '蒜蓉粉丝蒸扇贝',
    description: '海鲜美食，将蒜蓉、粉丝铺在扇贝上蒸制，鲜香可口，口感鲜嫩。',
    region: '广东',
    cuisine: '粤菜',
    difficulty: '中等',
    cookingTime: '20分钟',
    cookingTimeCategory: '适中',
    suitableFor: '上班族',
    spicyLevel: '不辣',
    ingredients: ['扇贝', '粉丝', '蒜', '葱', '生抽'],
    taste: ['鲜香', '咸鲜'],
    incompatibleWith: ['素食', '无海鲜'],
    reason: ''
  },
  {
    id: '8',
    name: '鱼香肉丝',
    description: '四川传统名菜，将肉丝与泡椒、木耳等一起炒制，咸甜酸辣，味道复杂。',
    region: '四川',
    cuisine: '川菜',
    difficulty: '中等',
    cookingTime: '25分钟',
    cookingTimeCategory: '适中',
    suitableFor: '上班族',
    spicyLevel: '中等',
    ingredients: ['猪里脊', '木耳', '胡萝卜', '泡椒', '葱姜蒜'],
    taste: ['咸鲜', '酸甜', '微辣'],
    incompatibleWith: ['素食'],
    reason: ''
  },
  {
    id: '9',
    name: '清蒸鲈鱼',
    description: '经典粤菜，保留了鲈鱼的原汁原味，鲜嫩可口，清淡健康。',
    region: '广东',
    cuisine: '粤菜',
    difficulty: '中等',
    cookingTime: '20分钟',
    cookingTimeCategory: '适中',
    suitableFor: '家庭主妇',
    spicyLevel: '不辣',
    ingredients: ['鲈鱼', '姜', '葱', '蒸鱼豉油', '香菜'],
    taste: ['清淡', '鲜香'],
    incompatibleWith: ['素食', '无海鲜'],
    reason: ''
  },
  {
    id: '10',
    name: '西红柿牛腩煲',
    description: '营养丰富的炖菜，牛腩炖至软烂，西红柿酸甜，汤汁鲜美。',
    region: '广东',
    cuisine: '粤菜',
    difficulty: '复杂',
    cookingTime: '90分钟',
    cookingTimeCategory: '耐心',
    suitableFor: '家庭主妇',
    spicyLevel: '不辣',
    ingredients: ['牛腩', '西红柿', '土豆', '胡萝卜', '洋葱'],
    taste: ['酸甜', '鲜香', '浓郁'],
    incompatibleWith: ['素食'],
    reason: ''
  },
  {
    id: '11',
    name: '蚂蚁上树',
    description: '川菜代表，将肉末炒香后加入粉丝，肉末附着在粉丝上，像是蚂蚁爬在树上。',
    region: '四川',
    cuisine: '川菜',
    difficulty: '简单',
    cookingTime: '15分钟',
    cookingTimeCategory: '快速',
    suitableFor: '上班族',
    spicyLevel: '中等',
    ingredients: ['猪肉末', '粉丝', '葱姜蒜', '郫县豆瓣', '酱油'],
    taste: ['麻辣', '鲜香'],
    incompatibleWith: ['素食'],
    reason: ''
  },
  {
    id: '12',
    name: '葱爆羊肉',
    description: '北方经典炒菜，羊肉鲜嫩，葱香浓郁，是冬季温补佳品。',
    region: '山东',
    cuisine: '鲁菜',
    difficulty: '中等',
    cookingTime: '20分钟',
    cookingTimeCategory: '适中',
    suitableFor: '上班族',
    spicyLevel: '不辣',
    ingredients: ['羊肉', '大葱', '姜', '料酒', '生抽'],
    taste: ['咸鲜', '浓郁'],
    incompatibleWith: ['素食'],
    reason: ''
  },
  {
    id: '13',
    name: '家常豆腐',
    description: '传统家常菜，豆腐与各种蔬菜一起烹饪，味道鲜美，适合各种场合。',
    region: '全国各地',
    cuisine: '家常菜',
    difficulty: '简单',
    cookingTime: '15分钟',
    cookingTimeCategory: '快速',
    suitableFor: '上班族',
    spicyLevel: '微辣',
    ingredients: ['豆腐', '青椒', '木耳', '葱姜蒜', '酱油'],
    taste: ['咸鲜', '微辣'],
    incompatibleWith: [],
    reason: ''
  },
  {
    id: '14',
    name: '椒盐虾',
    description: '酥脆可口的海鲜菜品，虾裹上椒盐面粉炸至金黄，外酥里嫩。',
    region: '广东',
    cuisine: '粤菜',
    difficulty: '中等',
    cookingTime: '20分钟',
    cookingTimeCategory: '适中',
    suitableFor: '家庭主妇',
    spicyLevel: '微辣',
    ingredients: ['大虾', '辣椒粉', '花椒粉', '淀粉', '葱'],
    taste: ['咸鲜', '微辣'],
    incompatibleWith: ['素食', '无海鲜'],
    reason: ''
  },
  {
    id: '15',
    name: '白切鸡',
    description: '粤菜代表，将鸡整只煮熟后切块，蘸料食用，保留了鸡肉的鲜嫩口感。',
    region: '广东',
    cuisine: '粤菜',
    difficulty: '中等',
    cookingTime: '40分钟',
    cookingTimeCategory: '耐心',
    suitableFor: '家庭主妇',
    spicyLevel: '不辣',
    ingredients: ['整鸡', '姜', '葱', '蒜蓉', '酱油'],
    taste: ['清淡', '鲜香'],
    incompatibleWith: ['素食'],
    reason: ''
  },
  {
    id: '16',
    name: '干煸四季豆',
    description: '经典素菜，将四季豆炸至皱皮后与调料一起干煸，外酥内嫩，香辣可口。',
    region: '四川',
    cuisine: '川菜',
    difficulty: '简单',
    cookingTime: '20分钟',
    cookingTimeCategory: '适中',
    suitableFor: '上班族',
    spicyLevel: '中等',
    ingredients: ['四季豆', '肉末', '干辣椒', '花椒', '盐'],
    taste: ['麻辣', '香脆'],
    incompatibleWith: [],
    reason: ''
  },
  {
    id: '17',
    name: '醋溜白菜',
    description: '东北家常菜，酸甜开胃，清脆爽口，是冬季常见的家常菜。',
    region: '东北',
    cuisine: '家常菜',
    difficulty: '简单',
    cookingTime: '10分钟',
    cookingTimeCategory: '快速',
    suitableFor: '上班族',
    spicyLevel: '不辣',
    ingredients: ['白菜', '醋', '糖', '淀粉', '胡萝卜'],
    taste: ['酸甜', '清淡'],
    incompatibleWith: [],
    reason: ''
  },
  {
    id: '18',
    name: '香菇青菜',
    description: '简单健康的素食菜品，香菇鲜香，青菜清脆，营养丰富。',
    region: '全国各地',
    cuisine: '家常菜',
    difficulty: '简单',
    cookingTime: '10分钟',
    cookingTimeCategory: '快速',
    suitableFor: '上班族',
    spicyLevel: '不辣',
    ingredients: ['香菇', '青菜', '蒜', '姜', '生抽'],
    taste: ['清淡', '鲜香'],
    incompatibleWith: [],
    reason: ''
  },
  {
    id: '19',
    name: '红烧排骨',
    description: '经典家常菜，排骨炖至软烂，汤汁浓郁，色泽红亮。',
    region: '江浙',
    cuisine: '苏菜',
    difficulty: '中等',
    cookingTime: '45分钟',
    cookingTimeCategory: '耐心',
    suitableFor: '家庭主妇',
    spicyLevel: '不辣',
    ingredients: ['排骨', '姜', '葱', '八角', '老抽'],
    taste: ['咸鲜', '浓郁'],
    incompatibleWith: ['素食', '低脂'],
    reason: ''
  },
  {
    id: '20',
    name: '鸡蛋炒饭',
    description: '家常快手菜，米饭与鸡蛋、葱花一起翻炒，简单美味，适合利用剩饭。',
    region: '全国各地',
    cuisine: '家常菜',
    difficulty: '简单',
    cookingTime: '10分钟',
    cookingTimeCategory: '快速',
    suitableFor: '上班族',
    spicyLevel: '不辣',
    ingredients: ['米饭', '鸡蛋', '葱', '盐', '生抽'],
    taste: ['咸鲜', '清淡'],
    incompatibleWith: ['素食'],
    reason: ''
  },
];